### PR TITLE
Add two new faces

### PR DESCRIPTION
**Pull request by mrcnski**
# PULL REQUEST

## Overview

Hi! Really enjoy this package, and I hope you like these changes.

## Changes

- Add `eshell-syntax-highlighting-argument-face` - for arguments starting with `-`, inherits from `font-lock-constant-face`. Got the idea from `shell-mode`.
- Add `eshell-syntax-highlighting-delimiter-face` - for [&|;], inherits from `default` to not add additional noise, so user must customize it. I saw that we already highlight delimiters with `'default`, so why not add a customizable face for it.

### CODE REVIEW

**Comment by akreisher** [comment]
Looks great, thanks!

**Comment by mrcnski** [comment]
Awesome!

But, I realized that "flag" would have been much better than "argument". Let me know what you think and I can quickly fix it, before another version is released.

**Comment by akreisher** [comment]
No worries, I renamed it to `eshell-syntax-highlighting-option-face`  here: https://github.com/akreisher/eshell-syntax-highlighting/commit/f38768bb3b557e884fdcc624daa3bce151279e0b

**Comment by mrcnski** [comment]
You rock. 🎸 Thanks!

**Pull request merged**
