### PR TITLE
Use an indirect buffer for Elisp highlighting

### LINKED ISSUE #14: Using `eshell-syntax-highlighting-highlight-elisp` breaks autocompletion
Hi. Using `eshell-syntax-highlighting-highlight-elisp` breaks Corfu, Company, and likely many other packages. I have linked this to a Doom Emacs PR here: https://github.com/doomemacs/doomemacs/pull/7529.

But basically, the way this syntax highlighting is implemented involves repeatedly deleting and re-inserting the Lisp expression but doing so causes a noticeable typing latency and breaks every package that uses markers or overlays to store state. In particular, this feature breaks `completion--in-region` so it basically breaks all incremental autocompletion in Eshell Elisp. Personally, I believe this is an unacceptable trade-off for getting Elisp syntax highlighting in Eshell and probably most users using this package have silently had their Elisp autocompletion broken without knowing as I did.

### PR DESCRIPTION
**Pull request by aikrahguzar**
I think this should fix #14 
Inspiration is from `comint-fontify-input-mode`.

### CODE REVIEW

**Comment by LemonBreezes** [comment]
This seems to work but has some edge case that is causing an error.
```elisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  eshell-syntax-highlighting--highlight-elisp(113 120)
  eshell-syntax-highlighting--parse-and-highlight(command 120)
  #<subr eshell-syntax-highlighting--enable-highlighting>()
  apply(#<subr eshell-syntax-highlighting--enable-highlighting> nil)
  (condition-case err (apply func args) ((debug error) (signal (car err) (cdr err))))
  cae-debug-reraise-error(#<subr eshell-syntax-highlighting--enable-highlighting>)
  apply(cae-debug-reraise-error #<subr eshell-syntax-highlighting--enable-highlighting> nil)
  eshell-syntax-highlighting--enable-highlighting()
```

EDIT: The issue is that for me, `comint--indirect-buffer` is nil.

Also, Less importantly, there is a typo in the name of the function `eshell-syntax-highlighting--indriect-buffer`.

**Comment by LemonBreezes** [comment]
The error is because `comint--indirect-buffer` should be `eshell-syntax-highlighting--indirect-lisp-buffer`.

**Comment by LemonBreezes** [comment]
Wow, and typing latency from this is in the 0.1 millisecond range, which is basically not noticeable, whereas the previous solution had very noticeable latency.

**Comment by LemonBreezes** [comment]
```diff
diff --git a/eshell-syntax-highlighting.el b/eshell-syntax-highlighting.el
index ab9b5bc..284b14e 100644
--- a/eshell-syntax-highlighting.el
+++ b/eshell-syntax-highlighting.el
@@ -167,17 +167,17 @@
            (t 'eshell-syntax-highlighting-default-face))))
     (add-face-text-property beg end face)))

-(defvar eshell-syntax-highlighting--indirect-lisp-buffer nil)
+(defvar-local eshell-syntax-highlighting--indirect-lisp-buffer nil)

 (defvar eshell-syntax-highlighting-indirect-buffer-setup-hook nil
   "Hook run to setup the in-direct buffer used for syntax highlighting Elisp.")

-(defun eshell-syntax-highlighting--indriect-buffer ()
+(defun eshell-syntax-highlighting--indirect-buffer ()
   "Return the indirect buffer for syntax highlighting."
   (if (buffer-live-p eshell-syntax-highlighting--indirect-lisp-buffer)
       eshell-syntax-highlighting--indirect-lisp-buffer
     (with-current-buffer
-        (setq-local eshell-syntax-highlighting--indirect-lisp-buffer
+        (setq eshell-syntax-highlighting--indirect-lisp-buffer
                     (make-indirect-buffer
                      (current-buffer)
                      (generate-new-buffer-name
@@ -197,7 +197,7 @@
     (let ((elisp-end (condition-case nil
                          (scan-sexps beg 1)
                        (scan-error end))))
-      (with-current-buffer (eshell-syntax-highlighting--indriect-buffer)
+      (with-current-buffer (eshell-syntax-highlighting--indirect-buffer)
         (narrow-to-region beg elisp-end)
         (font-lock-fontify-region beg elisp-end))
       (goto-char elisp-end))))
```

**Comment by aikrahguzar** [comment]
> The error is because `comint--indirect-buffer` should be `eshell-syntax-highlighting--indirect-lisp-buffer`.

I fixed that late yesterday, so please try with the latest. The typo should also be fixed now.

Other than that I favor not having local bindings in every buffer, which is why I went with `defvar` + `setq-local`, this way the variable has local bindings only in `eshell` buffers.

This is my interpretation of elisp manual saying,
```
The time to use ‘make-variable-buffer-local’ is when it is crucial
that no two buffers ever share the same binding.
```
whereas in this case most buffer should share the value `nil` and there is no reason to set it except by calling `eshell-syntax-highlighting--indirect-buffer` which will make it buffer local where it needs to be buffer local.

**Comment by aikrahguzar** [comment]
I really wish `set-buffer` emitted something other than `(wrong-type-argument stringp nil)` maybe `(wrong-type-argument string-or-buffer-p nil)` or even `(wrong-type-argument bufferp nil)`. This has confused me a few times by now and I never make the connection that the string is supposed to be buffer name especially since `set-buffer` itself tends not to show up in backtraces.

**Comment by LemonBreezes** [comment]
> > The error is because `comint--indirect-buffer` should be `eshell-syntax-highlighting--indirect-lisp-buffer`.
> 
> I fixed that late yesterday, so please try with the latest. The typo should also be fixed now.
> 
> Other than that I favor not having local bindings in every buffer, which is why I went with `defvar` + `setq-local`, this way the variable has local bindings only in `eshell` buffers.
> 
> This is my interpretation of elisp manual saying,
> 
> ```
> The time to use ‘make-variable-buffer-local’ is when it is crucial
> that no two buffers ever share the same binding.
> ```
> 
> whereas in this case most buffer should share the value `nil` and there is no reason to set it except by calling `eshell-syntax-highlighting--indirect-buffer` which will make it buffer local where it needs to be buffer local.

I guess that's fine. Not sure it makes a difference either way except that we're setting the variable as buffer local for each Eshell buffer rather than defining it as a local variable once and for all. But that's not important.

Yeah, the error was a bit tricky because it was in a post-command-hook but I got a backtrace using the trick from here https://gist.github.com/jdtsmith/1fbcacfe677d74bbe510aec80ac0050c and stepped through the highlighting function and realized it was the return value of `eshell-syntax-highlighting--indirect-buffer` that was nil. (It's also nice to use Eros while debugging to show the result in an overlay at the end of the line https://xenodium.com/inline-previous-result-and-why-you-should-edebug/). 

But yeah, I had no idea it was `set-buffer` either. It all comes down to this:
image
If it's a buffer, it returns, and then it checks if it's a string.

**Comment by LemonBreezes** [comment]
But yeah, I hope this PR gets merged soon!

**Comment by akreisher** [comment]
@aikrahguzar The changes here look good to me, although I will remove the `eshell-syntax-highlighting-indirect-buffer-setup-hook` variable, since I believe this is unused and likely leftover from the `comint-fontify-input-mode` (which I believe uses a hook to dynamically setup the buffer, which we don't do here). Please let me know if this should be re-added for some reason, thanks for the fix!

And @LemonBreezes thanks for reporting!

**Comment by aikrahguzar** [comment]
> @aikrahguzar The changes here look good to me, although I will remove the `eshell-syntax-highlighting-indirect-buffer-setup-hook` variable, since I believe this is unused and likely leftover from the `comint-fontify-input-mode` (which I believe uses a hook to dynamically setup the buffer, which we don't do here). Please let me know if this should be re-added for some reason, thanks for the fix!

@akreisher thanks! I am using `eshell-syntax-highlighting-indirect-buffer-setup-hook` to turn on `highlight-quoted-mode` in that buffer. I think it is useful for users to customize the highlighting in the same way they do in elisp files. Although since the buffer is setup only once maybe we should just run the mode hooks so that fontification in eshell buffers mirrors the elisp mirrors.

**Comment by akreisher** [comment]
> Although since the buffer is setup only once maybe we should just run the mode hooks so that fontification in eshell buffers mirrors the elisp mirrors.

Although I'd be inclined to this for simplicity, I'm not familiar enough with the implementation of indirect buffers to be sure that some emacs-lisp-mode hooks unrelated to highlighting may break things in the eshell buffer in unexpected ways. 

I think for now I will re-add the setup buffer hook function, and clarify its purpose in the docstring

**Comment by aikrahguzar** [comment]
> Although I'd be inclined to this for simplicity, I'm not familiar enough with the implementation of indirect buffers to be sure that some emacs-lisp-mode hooks unrelated to highlighting may break things in the eshell buffer in unexpected ways.

I think using `(narrow-to-region (point-max) (point-max)` before `(emacs-lisp-mode)` should make running most of hooks safe enough. I haven't tried it yet though.

**Comment by akreisher** [comment]
@aikrahguzar I re-added the hook, but I renamed it to `eshell-syntax-highlighting-elisp-buffer-setup-hook` to make it clearer that it affects elisp highlighting specifically.

**Comment by aikrahguzar** [comment]
> @aikrahguzar I re-added the hook, but I renamed it to `eshell-syntax-highlighting-elisp-buffer-setup-hook` to make it clearer that it affects elisp highlighting specifically.

Thanks!

**Pull request merged**
